steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_IMAGE_URI}:${SHORT_SHA}', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE_URI}:${SHORT_SHA}']
images:
  - '${_IMAGE_URI}:${SHORT_SHA}'
options:
  logging: CLOUD_LOGGING_ONLY
