apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: app
        image: asia-south1-docker.pkg.dev/firm-site-465207-c2/project1/node-app:v1
        ports:
        - containerPort: 8080
